name: Deploy on demo-test server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # зададим локальные env-переменные
    env:
      REMOTE_ARCHIVE: "app.tar.gz"
      REMOTE_TMP_DIR: "~/tmp/app"
      REMOTE_APP_DIR: "~/app"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create deployment archive
        run: |
          tar --exclude='.git' \
              --exclude='*/bin' \
              --exclude='*/obj' \
              --exclude='${{ env.REMOTE_ARCHIVE }}' \
              -czf /${{ env.REMOTE_ARCHIVE }} .
          mv /tmp/${{ env.REMOTE_ARCHIVE }} .
      
      - name: Ensure remote tmp directory
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ vars.DEPLOY_HOST }}
          username: ${{ vars.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
              mkdir -p ~/tmp    
